x-env: &env
  CARTESI_AUTH_KIND: private_key
  CARTESI_DATABASE_CONNECTION: postgres://postgres:password@database:5432/rollupsdb?sslmode=disable
  CARTESI_HTTP_ADDRESS: 0.0.0.0
  CARTESI_HTTP_PORT: 10012
  POSTGRES_PASSWORD: "password"

services:
  devnet:
    image: ghcr.io/prototyp3-dev/test-devnet:2.0.0
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8545/ -H 'Content-Type: application/json' -X POST --data '{\"jsonrpc\":\"2.0\",\"method\":\"eth_blockNumber\",\"params\":[],\"id\":67}'"]
      interval: 1s
      timeout: 1s
      retries: 5
    networks:
      - devnet
    ports:
      - 8545:8545

  database:
    image: postgres:16-alpine
    shm_size: 128mb
    networks:
      - devnet
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rollupsdb || exit 1"]
      interval: 3s
      timeout: 3s
      retries: 5
    environment:
      <<: *env
      POSTGRES_DB: rollupsdb

  espresso:
    image: ghcr.io/prototyp3-dev/test-node:2.0.0-alpha
    entrypoint: /init
    networks:
      - devnet
    ports:
      - 10040:10040
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:$${ESPRESSO_SEQUENCER_API_PORT}/v0/status/block-height"]
      interval: 1s
      timeout: 1s
      retries: 5
    volumes:
      - espresso_data:/mnt/espresso
    depends_on:
      devnet:
        condition: service_healthy
      database:
        condition: service_healthy
    environment:
      <<: *env
      ESPRESSO_SEQUENCER_L1_PROVIDER: http://devnet:8545
      ESPRESSO_SEQUENCER_API_PORT: 10040
      ESPRESSO_SEQUENCER_STORAGE_PATH: /mnt/espresso
      ESPRESSO_SEQUENCER_L1_POLLING_INTERVAL: "1s"
      ESPRESSO_STATE_PROVER_UPDATE_INTERVAL: "1s"
      ACTIVATE_CARTESI_NODE: false
      ACTIVATE_ESPRESSO_DEV_NODE: true
      ESPRESSO_DEV_NODE_L1_DEPLOYMENT: skip
      ESPRESSO_SEQUENCER_FEE_CONTRACT_ADDRESS: 0x0165878a594ca255338adfa4d48449f69242eb8f
      ESPRESSO_SEQUENCER_ESP_TOKEN_ADDRESS: 0x2279b7a0a67db372996a5fab50d91eaa73d2ebe6
      ESPRESSO_SEQUENCER_PLONK_VERIFIER_ADDRESS: 0x5fbdb2315678afecb367f032d93f642f64180aa3
      ESPRESSO_SEQUENCER_STAKE_TABLE_ADDRESS: 0x610178da211fef7d417bc0e6fed39f05609ad788
      ESPRESSO_SEQUENCER_ESP_TOKEN_PROXY_ADDRESS: 0x8a791620dd6260079bf849dc5567adc3f2fdc318
      ESPRESSO_SEQUENCER_LIGHT_CLIENT_PROXY_ADDRESS: 0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0
      ESPRESSO_SEQUENCER_FEE_CONTRACT_PROXY_ADDRESS: 0xa513e6e4b8f2a923d98304ec87f64353c4d5c853
      ESPRESSO_SEQUENCER_STAKE_TABLE_PROXY_ADDRESS: 0xb7f8bc63bbcad18155201308c8f3540b07f84f5e
      ESPRESSO_SEQUENCER_PLONK_VERIFIER_V2_ADDRESS: 0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9
    env_file:
     - ${ENVFILENAME}

  node:
    image: ghcr.io/prototyp3-dev/test-node:2.0.0-alpha
    entrypoint: /init
    healthcheck:
      test: ["CMD-SHELL", "curl -G -f -H 'Content-Type: application/json' http://127.0.0.1:$${CARTESI_HTTP_PORT}/healthz"]
      interval: 1s
      timeout: 1s
      retries: 5
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - node_data:/var/lib/cartesi-rollups-node/data
      - snapshots:/mnt/snapshots
      - apps:/mnt/apps
    networks:
      - devnet
    ports:
      - "8080:80"
    environment:
      <<: *env
    env_file:
     - ${ENVFILENAME}

volumes:
  node_data:
  snapshots:
  apps:
  espresso_data:

networks:
  devnet:
