name: test-images
run-name: Building Test Images
on:
  workflow_dispatch:

env:
  NODE_IMAGE_NAME: test-node
  CLOUD_NODE_IMAGE_NAME: test-node-cloud
  DEVNET_NAME: test-devnet

jobs:
  build-test-images:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    strategy:
      fail-fast: false
      matrix:
        images:
          - dockerfile: backend-node/backend-node.dockerfile
            target: rollups-node-we
          - dockerfile: backend-node/backend-node.dockerfile
            target: rollups-node-we-cloud
          - dockerfile: backend-node/devnet.dockerfile
            target: rollups-devnet-we

    steps:
      - name: Prepare
        run: |
          dockerfile=${{ matrix.images.dockerfile }}
          target=${{ matrix.images.target }}

      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Node Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
            images: |
                ghcr.io/prototyp3-dev/test-node
            tags: |
              type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
              type=ref,event=workflow_dispatch,enable=${{ github.ref != format('refs/heads/{0}', 'main') }}
              type=sha
            labels: |
              org.opencontainers.image.title=prototyp3-dev-test-node-cloud
              org.opencontainers.image.description=Test Node Cloud" 
              org.opencontainers.image.source=https://github.com/prototyp3-dev/node-recipes
              org.opencontainers.image.licenses=Apache-2.0
              org.opencontainers.image.url=https://github.com/prototyp3-dev/node-recipes

      - name: Node Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: ${{ matrix.images.target }}
          file: ${{ matrix.images.dockerfile }}
